// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMFa18AsvAkARwiEV4BlCQjFKe4CX89w8',
    appId: '1:980676340958:web:c08ebdc35b72f5534aa64f',
    messagingSenderId: '980676340958',
    projectId: 'cs184-final',
    authDomain: 'cs184-final.firebaseapp.com',
    databaseURL: 'https://cs184-final-default-rtdb.firebaseio.com',
    storageBucket: 'cs184-final.appspot.com',
    measurementId: 'G-FW42BNSGHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg9IcP06apnQ-k3rwoUDopKS-H6MsaAvo',
    appId: '1:980676340958:android:97640ed7725f988b4aa64f',
    messagingSenderId: '980676340958',
    projectId: 'cs184-final',
    databaseURL: 'https://cs184-final-default-rtdb.firebaseio.com',
    storageBucket: 'cs184-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQCMoFgjLkttVKGx4uYU_xRAzdCYnayXk',
    appId: '1:980676340958:ios:763a5bbaf1cf88c14aa64f',
    messagingSenderId: '980676340958',
    projectId: 'cs184-final',
    databaseURL: 'https://cs184-final-default-rtdb.firebaseio.com',
    storageBucket: 'cs184-final.appspot.com',
    iosClientId: '980676340958-g7d1p3k8bkprk248vfthqk8jeb5tnl7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.cs184',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQCMoFgjLkttVKGx4uYU_xRAzdCYnayXk',
    appId: '1:980676340958:ios:763a5bbaf1cf88c14aa64f',
    messagingSenderId: '980676340958',
    projectId: 'cs184-final',
    databaseURL: 'https://cs184-final-default-rtdb.firebaseio.com',
    storageBucket: 'cs184-final.appspot.com',
    iosClientId: '980676340958-g7d1p3k8bkprk248vfthqk8jeb5tnl7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.cs184',
  );
}
